name: Build & Release
on:
  workflow_dispatch:
    inputs:
      external_url:
        required: true
      build_flg:
jobs:
  build-release:
    runs-on: macos-latest
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=${{ github.event.repository.name }}_$(date +'%Y-%m-%d_%H-%m-%S')" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: itsnebulalol/permasigner

      - name: Install dpkg
        run: brew install dpkg

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Build
        run: python3 main.py ${{ github.event.inputs.build_flg }} -u ${{ github.event.inputs.external_url }}

      - name: Release
        uses: ncipollo/release-action@v1.10.0
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "output/*.deb"
